# Generated by Django 4.1 on 2024-01-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='folder name')),
                ('recycle_bin', models.BooleanField(default=False, verbose_name='folder in recycle bin')),
                ('star', models.BooleanField(default=False, verbose_name='starred')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_api.folder', verbose_name='parent folder id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='file name')),
                ('path', models.FileField(upload_to='files/', verbose_name='path to file')),
                ('recycle_bin', models.BooleanField(default=False, verbose_name='file in recycle bin')),
                ('star', models.BooleanField(default=False, verbose_name='starred')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_api.file', verbose_name='parent folder id')),
            ],
        ),
    ]
