# Generated by Django 4.1 on 2024-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(verbose_name='file size'),
        ),
    ]
