# Generated by Django 4.1 on 2024-02-02 19:29

from django.db import migrations, models
import storage_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0003_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=storage_api.models.user_files_dir_path, verbose_name='path to file'),
        ),
    ]
