# Generated by Django 4.1 on 2024-02-07 20:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default_user_profile_photo.png', max_length=255, null=True, upload_to=users.models.profile_photo_dir_path, verbose_name='profile photo'),
        ),
    ]
